const SKILL_LIB = {
    ableton: { name: "Ableton", icon: "ableton" },
    activitypub: { name: "ActivityPub", icon: "activitypub" },
    actix: { name: "Actix", icon: "actix" },
    adonis: { name: "Adonis", icon: "adonis" },
    ae: { name: "After Effects", icon: "ae" },
    aiscript: { name: "AIScript", icon: "aiscript" },
    alpinejs: { name: "Alpine.js", icon: "alpinejs" },
    anaconda: { name: "Anaconda", icon: "anaconda" },
    androidstudio: { name: "Android Studio", icon: "androidstudio" },
    angular: { name: "Angular", icon: "angular" },
    ansible: { name: "Ansible", icon: "ansible" },
    apollo: { name: "Apollo", icon: "apollo" },
    apple: { name: "Apple", icon: "apple" },
    appwrite: { name: "Appwrite", icon: "appwrite" },
    arch: { name: "Arch Linux", icon: "arch" },
    arduino: { name: "Arduino", icon: "arduino" },
    astro: { name: "Astro", icon: "astro" },
    atom: { name: "Atom", icon: "atom" },
    au: { name: "Audacity", icon: "au" },
    autocad: { name: "AutoCAD", icon: "autocad" },
    aws: { name: "AWS", icon: "aws" },
    azul: { name: "Azul", icon: "azul" },
    azure: { name: "Azure", icon: "azure" },
    babel: { name: "Babel", icon: "babel" },
    bash: { name: "Bash", icon: "bash" },
    bevy: { name: "Bevy", icon: "bevy" },
    bitbucket: { name: "Bitbucket", icon: "bitbucket" },
    blender: { name: "Blender", icon: "blender" },
    bootstrap: { name: "Bootstrap", icon: "bootstrap" },
    bsd: { name: "BSD", icon: "bsd" },
    bun: { name: "Bun", icon: "bun" },
    c: { name: "C", icon: "c" },
    cs: { name: "C#", icon: "cs" },
    cpp: { name: "C++", icon: "cpp" },
    crystal: { name: "Crystal", icon: "crystal" },
    cassandra: { name: "Cassandra", icon: "cassandra" },
    clion: { name: "CLion", icon: "clion" },
    clojure: { name: "Clojure", icon: "clojure" },
    cloudflare: { name: "Cloudflare", icon: "cloudflare" },
    cmake: { name: "CMake", icon: "cmake" },
    codepen: { name: "CodePen", icon: "codepen" },
    coffeescript: { name: "CoffeeScript", icon: "coffeescript" },
    css: { name: "CSS", icon: "css" },
    cypress: { name: "Cypress", icon: "cypress" },
    d3: { name: "D3.js", icon: "d3" },
    dart: { name: "Dart", icon: "dart" },
    debian: { name: "Debian", icon: "debian" },
    deno: { name: "Deno", icon: "deno" },
    devto: { name: "Dev.to", icon: "devto" },
    discord: { name: "Discord", icon: "discord" },
    bots: { name: "Discord Bots", icon: "bots" },
    discordjs: { name: "Discord.js", icon: "discordjs" },
    django: { name: "Django", icon: "django" },
    docker: { name: "Docker", icon: "docker" },
    dotnet: { name: ".NET", icon: "dotnet" },
    dynamodb: { name: "DynamoDB", icon: "dynamodb" },
    eclipse: { name: "Eclipse", icon: "eclipse" },
    elasticsearch: { name: "Elasticsearch", icon: "elasticsearch" },
    electron: { name: "Electron", icon: "electron" },
    elixir: { name: "Elixir", icon: "elixir" },
    elysia: { name: "Elysia", icon: "elysia" },
    emacs: { name: "Emacs", icon: "emacs" },
    ember: { name: "Ember.js", icon: "ember" },
    emotion: { name: "Emotion", icon: "emotion" },
    express: { name: "Express", icon: "express" },
    fastapi: { name: "FastAPI", icon: "fastapi" },
    fediverse: { name: "Fediverse", icon: "fediverse" },
    figma: { name: "Figma", icon: "figma" },
    firebase: { name: "Firebase", icon: "firebase" },
    flask: { name: "Flask", icon: "flask" },
    flutter: { name: "Flutter", icon: "flutter" },
    forth: { name: "Forth", icon: "forth" },
    fortran: { name: "Fortran", icon: "fortran" },
    gamemakerstudio: { name: "GameMaker Studio", icon: "gamemakerstudio" },
    gatsby: { name: "Gatsby", icon: "gatsby" },
    gcp: { name: "Google Cloud", icon: "gcp" },
    git: { name: "Git", icon: "git" },
    github: { name: "GitHub", icon: "github" },
    githubactions: { name: "GitHub Actions", icon: "githubactions" },
    gitlab: { name: "GitLab", icon: "gitlab" },
    gmail: { name: "Gmail", icon: "gmail" },
    gherkin: { name: "Gherkin", icon: "gherkin" },
    go: { name: "Go", icon: "go" },
    gradle: { name: "Gradle", icon: "gradle" },
    godot: { name: "Godot", icon: "godot" },
    grafana: { name: "Grafana", icon: "grafana" },
    graphql: { name: "GraphQL", icon: "graphql" },
    gtk: { name: "GTK", icon: "gtk" },
    gulp: { name: "Gulp", icon: "gulp" },
    haskell: { name: "Haskell", icon: "haskell" },
    haxe: { name: "Haxe", icon: "haxe" },
    haxeflixel: { name: "HaxeFlixel", icon: "haxeflixel" },
    heroku: { name: "Heroku", icon: "heroku" },
    hibernate: { name: "Hibernate", icon: "hibernate" },
    html: { name: "HTML", icon: "html" },
    htmx: { name: "HTMX", icon: "htmx" },
    idea: { name: "IntelliJ IDEA", icon: "idea" },
    ai: { name: "Illustrator", icon: "ai" },
    instagram: { name: "Instagram", icon: "instagram" },
    ipfs: { name: "IPFS", icon: "ipfs" },
    java: { name: "Java", icon: "java" },
    js: { name: "JavaScript", icon: "js" },
    jenkins: { name: "Jenkins", icon: "jenkins" },
    jest: { name: "Jest", icon: "jest" },
    jquery: { name: "jQuery", icon: "jquery" },
    kafka: { name: "Kafka", icon: "kafka" },
    kali: { name: "Kali Linux", icon: "kali" },
    kotlin: { name: "Kotlin", icon: "kotlin" },
    ktor: { name: "Ktor", icon: "ktor" },
    kubernetes: { name: "Kubernetes", icon: "kubernetes" },
    laravel: { name: "Laravel", icon: "laravel" },
    latex: { name: "LaTeX", icon: "latex" },
    less: { name: "Less", icon: "less" },
    linkedin: { name: "LinkedIn", icon: "linkedin" },
    linux: { name: "Linux", icon: "linux" },
    lit: { name: "Lit", icon: "lit" },
    lua: { name: "Lua", icon: "lua" },
    md: { name: "Markdown", icon: "md" },
    mastodon: { name: "Mastodon", icon: "mastodon" },
    materialui: { name: "Material-UI", icon: "materialui" },
    matlab: { name: "MATLAB", icon: "matlab" },
    maven: { name: "Maven", icon: "maven" },
    mint: { name: "Mint", icon: "mint" },
    misskey: { name: "Misskey", icon: "misskey" },
    mongodb: { name: "MongoDB", icon: "mongodb" },
    mysql: { name: "MySQL", icon: "mysql" },
    neovim: { name: "Neovim", icon: "neovim" },
    nestjs: { name: "NestJS", icon: "nestjs" },
    netlify: { name: "Netlify", icon: "netlify" },
    nextjs: { name: "Next.js", icon: "nextjs" },
    nginx: { name: "NGINX", icon: "nginx" },
    nim: { name: "Nim", icon: "nim" },
    nix: { name: "Nix", icon: "nix" },
    nodejs: { name: "Node.js", icon: "nodejs" },
    notion: { name: "Notion", icon: "notion" },
    npm: { name: "npm", icon: "npm" },
    nuxtjs: { name: "Nuxt.js", icon: "nuxtjs" },
    obsidian: { name: "Obsidian", icon: "obsidian" },
    ocaml: { name: "OCaml", icon: "ocaml" },
    octave: { name: "Octave", icon: "octave" },
    opencv: { name: "OpenCV", icon: "opencv" },
    openshift: { name: "OpenShift", icon: "openshift" },
    openstack: { name: "OpenStack", icon: "openstack" },
    p5js: { name: "p5.js", icon: "p5js" },
    perl: { name: "Perl", icon: "perl" },
    ps: { name: "Photoshop", icon: "ps" },
    php: { name: "PHP", icon: "php" },
    phpstorm: { name: "PhpStorm", icon: "phpstorm" },
    pinia: { name: "Pinia", icon: "pinia" },
    pkl: { name: "Pkl", icon: "pkl" },
    plan9: { name: "Plan 9", icon: "plan9" },
    planetscale: { name: "PlanetScale", icon: "planetscale" },
    pnpm: { name: "pnpm", icon: "pnpm" },
    postgres: { name: "PostgreSQL", icon: "postgres" },
    postman: { name: "Postman", icon: "postman" },
    powershell: { name: "PowerShell", icon: "powershell" },
    pr: { name: "Premiere Pro", icon: "pr" },
    prisma: { name: "Prisma", icon: "prisma" },
    processing: { name: "Processing", icon: "processing" },
    prometheus: { name: "Prometheus", icon: "prometheus" },
    pug: { name: "Pug", icon: "pug" },
    pycharm: { name: "PyCharm", icon: "pycharm" },
    py: { name: "Python", icon: "py" },
    pytorch: { name: "PyTorch", icon: "pytorch" },
    qt: { name: "Qt", icon: "qt" },
    r: { name: "R", icon: "r" },
    rabbitmq: { name: "RabbitMQ", icon: "rabbitmq" },
    rails: { name: "Ruby on Rails", icon: "rails" },
    raspberrypi: { name: "Raspberry Pi", icon: "raspberrypi" },
    react: { name: "React", icon: "react" },
    reactivex: { name: "ReactiveX", icon: "reactivex" },
    redhat: { name: "Red Hat", icon: "redhat" },
    redis: { name: "Redis", icon: "redis" },
    redux: { name: "Redux", icon: "redux" },
    regex: { name: "Regex", icon: "regex" },
    remix: { name: "Remix", icon: "remix" },
    replit: { name: "Replit", icon: "replit" },
    rider: { name: "Rider", icon: "rider" },
    robloxstudio: { name: "Roblox Studio", icon: "robloxstudio" },
    rocket: { name: "Rocket", icon: "rocket" },
    rollupjs: { name: "Rollup.js", icon: "rollupjs" },
    ros: { name: "ROS", icon: "ros" },
    ruby: { name: "Ruby", icon: "ruby" },
    rust: { name: "Rust", icon: "rust" },
    sass: { name: "Sass", icon: "sass" },
    spring: { name: "Spring", icon: "spring" },
    sqlite: { name: "SQLite", icon: "sqlite" },
    stackoverflow: { name: "Stack Overflow", icon: "stackoverflow" },
    styledcomponents: { name: "Styled Components", icon: "styledcomponents" },
    sublime: { name: "Sublime Text", icon: "sublime" },
    supabase: { name: "Supabase", icon: "supabase" },
    scala: { name: "Scala", icon: "scala" },
    sklearn: { name: "Scikit-learn", icon: "sklearn" },
    selenium: { name: "Selenium", icon: "selenium" },
    sentry: { name: "Sentry", icon: "sentry" },
    sequelize: { name: "Sequelize", icon: "sequelize" },
    sketchup: { name: "SketchUp", icon: "sketchup" },
    solidity: { name: "Solidity", icon: "solidity" },
    solidjs: { name: "SolidJS", icon: "solidjs" },
    svelte: { name: "Svelte", icon: "svelte" },
    svg: { name: "SVG", icon: "svg" },
    swift: { name: "Swift", icon: "swift" },
    symfony: { name: "Symfony", icon: "symfony" },
    tailwind: { name: "Tailwind CSS", icon: "tailwind" },
    tauri: { name: "Tauri", icon: "tauri" },
    tensorflow: { name: "TensorFlow", icon: "tensorflow" },
    terraform: { name: "Terraform", icon: "terraform" },
    threejs: { name: "Three.js", icon: "threejs" },
    twitter: { name: "Twitter", icon: "twitter" },
    ts: { name: "TypeScript", icon: "ts" },
    ubuntu: { name: "Ubuntu", icon: "ubuntu" },
    unity: { name: "Unity", icon: "unity" },
    unreal: { name: "Unreal Engine", icon: "unreal" },
    v: { name: "V", icon: "v" },
    vala: { name: "Vala", icon: "vala" },
    vercel: { name: "Vercel", icon: "vercel" },
    vim: { name: "Vim", icon: "vim" },
    visualstudio: { name: "Visual Studio", icon: "visualstudio" },
    vite: { name: "Vite", icon: "vite" },
    vitest: { name: "Vitest", icon: "vitest" },
    vscode: { name: "VS Code", icon: "vscode" },
    vscodium: { name: "VSCodium", icon: "vscodium" },
    vue: { name: "Vue.js", icon: "vue" },
    vuetify: { name: "Vuetify", icon: "vuetify" },
    wasm: { name: "WebAssembly", icon: "wasm" },
    webflow: { name: "Webflow", icon: "webflow" },
    webpack: { name: "Webpack", icon: "webpack" },
    webstorm: { name: "WebStorm", icon: "webstorm" },
    windicss: { name: "Windi CSS", icon: "windicss" },
    windows: { name: "Windows", icon: "windows" },
    wordpress: { name: "WordPress", icon: "wordpress" },
    workers: { name: "Cloudflare Workers", icon: "workers" },
    xd: { name: "Adobe XD", icon: "xd" },
    yarn: { name: "Yarn", icon: "yarn" },
    yew: { name: "Yew", icon: "yew" },
    zig: { name: "Zig", icon: "zig" }
  };
  
  function buildTheIconLink(skills, options = {}) {
    const { theme = "dark", perline = 15, centered = false } = options;
    
    // Validate inputs
    if (!Array.isArray(skills)) {
      throw new Error("Skills must be provided as an array");
    }
    
    // Filter valid skills and map to their icon IDs
    const validSkills = skills
      .map(skill => skill.toLowerCase())
      .filter(skill => SKILL_LIB[skill])
      .join(",");
    
    if (!validSkills) {
      throw new Error("No valid skills provided");
    }
    
    // Validate theme
    if (!["dark", "light"].includes(theme)) {
      throw new Error("Theme must be either 'dark' or 'light'");
    }
    
    // Validate perline
    const perlineNum = parseInt(perline, 10);
    if (isNaN(perlineNum) || perlineNum < 1 || perlineNum > 50) {
      throw new Error("perline must be a number between 1 and 50");
    }
    
    // Build the URL
    let url = `https://skillicons.dev/icons?i=${validSkills}&theme=${theme}&perline=${perlineNum}`;
    
    // Return markdown based on centering option
    if (centered) {
      return `
  <p align="center">
    <a href="https://skillicons.dev">
      <img src="${url}" />
    </a>
  </p>
  `;
    }
    
    return `[![My Skills](${url})](https://skillicons.dev)`;
  }

export { SKILL_LIB, buildTheIconLink };